export enum ConfigKeys {
    PORT = 'PORT',
    HOST = 'HOST',
    USERNAME = 'USERNAME',
    PASSWORD = 'PASSWORD',
    DATABASE = 'DATABASE',
    PORT_DATABASE = 'PORT_DATABASE',
    JWT_SECRET = "JWT_SECRET",
    SEND_GRID_API_KEY = "SEND_GRID_API_KEY",
    POEDITOR = "POEDITOR_KEY",
    POEDITOR_PROJECT = "POEDITOR_PROJECT",
}