export enum ConfigKeys {
    PORT = 'PORT',
    HOST = 'HOST',
    USERNAME = 'USERNAME',
    PASSWORD = 'PASSWORD',
    DATABASE = 'DATABASE',
    JWT_SECRET = "JWT_SECRET",
    SEND_GRID_API_KEY = "SEND_GRID_API_KEY"
}