export const PRODUCTS_DETAIL_FETCH_PRODUCT = 'PRODUCTS_DETAIL_FETCH_PRODUCT';
export const PRODUCT_DETAIL_UPDATE_PRODUCT = 'PRODUCT_DETAIL_UPDATE_PRODUCT';
export const PRODUCT_DETAIL_DELETE_IMAGES = 'PRODUCT_DETAIL_DELETE_IMAGES';
export const PRODUCT_DETAIL_ADD_IMAGES = 'PRODUCT_DETAIL_ADD_IMAGES';
export const PRODUCT_DETAIL_DELETE_PRODUCT = 'PRODUCT_DETAIL_DELETE_PRODUCT';
