export const PRODUCTS_VIEW_FETCH_ALL_PRODUCTS = "PRODUCTS_VIEW_FETCH_ALL_PRODUCTS";
export const PRODUCTS_VIEW_CHANGE_PAGE = "PRODUCTS_VIEW_CHANGE_PAGE";
export const PRODUCTS_VIEW_SEARCH = "PRODUCTS_VIEW_SEARCH";
export const PRODUCTS_VIEW_SEARCH_BY_FILTERS = "PRODUCTS_VIEW_SEARCH_BY_FILTERS";