export const LIST_OF_PRODUCTS = "LIST_OF_PRODUCTS";
export const HOW_MANY_PAGES_ARE = "HOW_MANY_PAGES_ARE";
export const GET_TOTAL_PRODUCTS = "GET_TOTAL_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SEARCH = "GET_SEARCH";