<template>
    <div class="flex">
        <div class="loadingio-spinner-dual-ring-h4jkonjv3gk">
            <div class="ldio-3hgj91t72k">
                <div></div>
                <div><div></div></div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';

@Component({
    components: {}
})
export default class Loader extends Vue {}
</script>

<style>
@keyframes ldio-3hgj91t72k {
    0% {
        transform: rotate(0);
    }
    100% {
        transform: rotate(360deg);
    }
}
.ldio-3hgj91t72k div {
    box-sizing: border-box !important;
}
.ldio-3hgj91t72k > div {
    position: absolute;
    width: 144px;
    height: 144px;
    top: 28px;
    left: 28px;
    border-radius: 50%;
    border: 16px solid #000;
    border-color: #f58c51 transparent #f58c51 transparent;
    animation: ldio-3hgj91t72k 1s linear infinite;
}
.ldio-3hgj91t72k > div:nth-child(2) {
    border-color: transparent;
}
.ldio-3hgj91t72k > div:nth-child(2) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
}
.ldio-3hgj91t72k > div:nth-child(2) div:before,
.ldio-3hgj91t72k > div:nth-child(2) div:after {
    content: '';
    display: block;
    position: absolute;
    width: 16px;
    height: 16px;
    top: -16px;
    left: 48px;
    border-radius: 50%;
    box-shadow: 0 128px 0 0 #f58c51;
}
.ldio-3hgj91t72k > div:nth-child(2) div:after {
    left: -16px;
    top: 48px;
    box-shadow: 128px 0 0 0 #f58c51;
}
.loadingio-spinner-dual-ring-h4jkonjv3gk {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
}
.ldio-3hgj91t72k {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
.ldio-3hgj91t72k div {
    box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
